server:
  port: 8081
  session-timeout: 30
  tomcat.max-threads : 0
  tomcat.uri-encoding : UTF-8

spring:
  datasource:
    url: jdbc:mysql://cdb-rm2lg37n.gz.tencentcdb.com:10051/thead_pool?characterEncoding=utf-8&useSSL=false
    username : root
    password : 5201314Ss
    driverClassName : com.mysql.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.example.testspringboot.entity.TheadDO
  mapper-locations: classpath:mapper/*.xml
